# Developing a topic

As explained in the project overview, you are able to select any topic in ecology to focus on!

Your questions may address any topic in ecology - examining how organisms relate to one another and to their environment. The only qualifier is that there must be enough literature published on the topic to generate novel insights, by examining and summarizing the literature.

As **examples**, here are some questions from previous years:

- How will climate change affect Pinyon species in the Southwest?
- What factors lead to successful restoration after Ponderosa pine fire?
- How does shark behavior vary in response to human development?

There are no right or wrong questions - please choose something of interest to you!

## Procedure

Break into groups and start to develop a research question. During the literature search phase of the project, you will refine this question, but first you must agree on a topic area to focus on!

## Deliverables

Submit a tentative research question via the Canvas portal.
